language: go
go:
  - master

git:
 submodules: false

before_install:
  - sudo apt-get install lftp

install:
  - go get github.com/gohugoio/hugo

script:
  - sh scripts/deploy.sh

deploy:
  provider: pages
  skip_cleanup: true
  github_token: $GITHUB_TOKEN
  local_dir: prod
  on:
    branch: master