language: go
go:
  - master

install:
  - go get github.com/gohugoio/hugo

script:
  - rm -rf prod || exit 0
  - cd site
  - hugo 

deploy:
  provider: pages
  skip_cleanup: true
  github_token: $GITHUB_TOKEN
  local_dir: prod
  on:
    branch: master