language: go
go:
  - master

before_install:
  - sudo apt-get install lftp

install:
  - go get github.com/gohugoio/hugo

script:
  - cd site
  - hugo 
  - cd ..
  - lftp -e "open sftp://$USER:$PASSWORD@$SITE; mirror --verbose --reverse prod /$TARGET;bye;"

deploy:
  provider: pages
  skip_cleanup: true
  github_token: $GITHUB_TOKEN
  local_dir: prod
  on:
    branch: master