language: go
go:
  - master

git:
 submodules: false

before_install:
  - sudo apt-get install lftp
  - git config --file=.gitmodules submodule.site/themes/after-dark.url https://github.com/ITSocietyMMUMelaka/after-dark.git
  - git submodule update --init --recursive
  - sh scripts/update-git-info.sh

install:
  - go get github.com/gohugoio/hugo
  - hugo version

script:
  - cd site
  - hugo 
  - cd ..
  - lftp -e "open sftp://$USERNAME:$PASSWORD@$SITE; rm -rf $TARGETFOLDER; mirror --verbose --reverse prod /$TARGETFOLDER;bye;"
  - cd site
  - sed -i "s/http:\/\/beta.itsociety.club\//https:\/\/itsocietymmumelaka.github.io\/beta\//g" config.toml
  - hugo  # second build for GitHub pages  
  - cd ..

deploy:
  provider: pages
  skip_cleanup: true
  github_token: $GITHUB_TOKEN
  local_dir: prod
  on:
    branch: master