language: go
go:
  - master

before_install:
  - sudo apt-get install lftp
  - git config --file=.gitmodules submodule.site/themes/after-dark.url https://github.com/ITSocietyMMUMelaka/beta.git

install:
  - go get github.com/gohugoio/hugo

script:
  - cd site
  - hugo 
  - cd ..
  - lftp -e "open sftp://$USERNAME:$PASSWORD@$SITE; mirror --verbose --reverse prod /$TARGETFOLDER;bye;"

deploy:
  provider: pages
  skip_cleanup: true
  github_token: $GITHUB_TOKEN
  local_dir: prod
  on:
    branch: master