language: go
sudo: true
dist: trusty

install:
  - sudo apt-get --yes install snapd
  - sudo snap install hugo
  - rm -rf prod || exit 0

script:
  - cd site
  - hugo 

deploy:
  provider: pages
  skip_cleanup: true
  github_token: $GITHUB_TOKEN
  local_dir: prod
  on:
    branch: master