addons:
  apt:
    packages:
    - hugo

install:
  - rm -rf prod || exit 0

script:
  - hugo

deploy:
  provider: pages
  skip_cleanup: true
  github_token: $GITHUB_TOKEN
  local_dir: prod
  on:
    branch: master