language: go
go:
  - master

install:
  - go get github.com/gohugoio/hugo

script:
  - ls
  - cd site
  - ls
  - hugo 
  - cd ..

deploy:
  provider: pages
  skip_cleanup: true
  github_token: $GITHUB_TOKEN
  local_dir: prod
  on:
    branch: master